[sdl]
fullscreen=false
output=surface
autolock=false
showmenu=false
waitonerror=false
[dosbox]
machine=vgaonly
memsize=16
captures=D:\Progs\OR\financial_market_simulator\tests\reference_cases\captures
[cpu]
core=normal
cycles=fixed 10000
[render]
aspect=false
scaler=none
[autoexec]
mount c D:\Progs\OR\financial_market_simulator\data\reference_work
c:
imgmount a D:\Progs\OR\fik.img -t floppy -ro
keyrus /files
keyrus /8x16=on /all
stend.exe
